// src/components/Setting.tsx
import { auth } from '@/services/cloud'

export default function Setting() {

  const onLogout = () => {
    auth.signOut()
      .then(() => {
        localStorage.removeItem('attraction')
        location.href = import.meta.env.BASE_URL
      })
  }
  return <>
    <button className="btn btn-secondary" onClick={onLogout}>退出</button >
  </>
}

// src/components/App/Setting.vue
<script lang="ts" setup>
import { ref } from 'vue'
import lc from '@/libs/lc'

function onLogout() {
  lc.logout()
  localStorage.removeItem('attraction')
  location.href = import.meta.env.BASE_URL + 'login/'
}
</script>

<template>
  <div>
    <el-button type="primary" @click="onLogout">退出</el-button>
  </div>
</template>

<style></style>
