// src/components/Area/Query.tsx
import { FormEvent, useState } from "react"

export default function Query(props: { onAdd: (e: FormEvent) => void }) {
  const { onAdd } = props
  const [searchName, setSearchName] = useState('')

  return <>
    <form className="demo-form-inline" onSubmit={onAdd}>
      <label>
        <input id="searchName" value={searchName} placeholder="输入自动搜索" onChange={(e) => setSearchName(e.target.value)}
          className="input input-bordered w-full max-w-xs" />
      </label>
      <label className=" ml-2">
        <button className="btn btn-primary" type="submit">新增</button>
      </label>
    </form>
  </>
}

// src/components/App/Toilet/Query.vue
<script lang="ts" setup>
import { inject } from 'vue'
import type { Ref } from 'vue'
const searchParams = inject('searchParams') as Ref<ToiletSearchParams>

const emit = defineEmits(['add'])

function onAdd() {
  emit('add')
}
</script>

<template>
  <el-form :inline="true" :model="searchParams" class="demo-form-inline">
    <el-form-item label="厕所名称">
      <el-input v-model="searchParams.name" placeholder="输入自动搜索" />
    </el-form-item>
    <el-form-item>
      <el-button type="primary" @click="onAdd">新增</el-button>
    </el-form-item>
  </el-form>
</template>

<style scoped></style>
