// src/components/Area.tsx
import Query from '@/components/Area/Query'
import { FormEvent } from 'react'

export default function Area() {
  const onAdd = (e: FormEvent) => {
    e.preventDefault()
    console.log('add')
  }
  return <>
    <Query onAdd={onAdd} />
    {/* <List @lnglat="onReviewLnglat" @edit="onCellEdit" />
  <Edit v-model:visible="editVisible" v-model:lnglat="currentLnglat" :editData="editData" @confirm="onEditConfirm"
    @showmap="onShowMap" />
  <Map :visible="dialogMapVisible" :defaultLnglat="defaultLnglat" @choose="doChooseLnglat" @close="onCloseMap" /> */}
  </>
}

// src/components/Area.vue
<script lang="ts" setup>
import { ref, provide, nextTick } from 'vue'
import Query from '@/components/Area/Query.vue'
import List from '@/components/Area/List.vue'
import Edit from '@/components/Area/Edit.vue'
import Map from '@/components/Common/Map.vue'

const currentLnglat = ref<Lnglat | null>(null)
const editData = ref<Area | null>(null)

const searchParams = ref<AreaSearchParams>({ name: '' })
provide('searchParams', searchParams)

function onAdd() {
  editData.value = null
  editVisible.value = true
}

// 地图
const dialogMapVisible = ref(false)
const defaultLnglat = ref<Lnglat | null>(null)

function onReviewLnglat(ll: LL) {
  defaultLnglat.value = ll
  onShowMap()
}

function onShowMap(lnglat?: Lnglat) {
  dialogMapVisible.value = true
  if (lnglat) {
    defaultLnglat.value = lnglat
  }
}

function onCloseMap() {
  dialogMapVisible.value = false
}

function doChooseLnglat(lnglat: Lnglat) {
  currentLnglat.value = lnglat
  dialogMapVisible.value = false
}

// 编辑(新增)
const editVisible = ref(false)

function onEditConfirm() {
  doUpdateList()
}

// 通过改变搜索条件来更新列表
async function doUpdateList() {
  let tempName = searchParams.value.name
  searchParams.value.name = '@$%^!@^%$#!@'
  await nextTick()
  searchParams.value.name = tempName
}

function onCellEdit(data: Area) {
  editVisible.value = true
  editData.value = data
  console.log('选择景点: ' + data.name)
  console.log(data)
}
</script>

<template>
  <Query @add="onAdd" />
  <List @lnglat="onReviewLnglat" @edit="onCellEdit" />
  <Edit v-model:visible="editVisible" v-model:lnglat="currentLnglat" :editData="editData" @confirm="onEditConfirm"
    @showmap="onShowMap" />
  <Map :visible="dialogMapVisible" :defaultLnglat="defaultLnglat" @choose="doChooseLnglat" @close="onCloseMap" />
</template>

<style></style>
